### PR TITLE
UCCSD Bug Fixes #952

### LINKED ISSUE #952: UCCSD code in the latest version (0.4.1) is incorrect
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The coupled cluster wave function can be written as following:

image

When we convert from fermionin to qubit using jordan wigner we obtain

image

Currently, if you check the UCCSD code [(https://github.com/NVIDIA/cuda-quantum/blob/main/runtime/cudaq/domains/chemistry/uccsd.h)](url) you will find that you only implemented the  X and Y operator but not thee Z operator. This leads to incorrect result. 

Note that the UCCSD in the previous version 0.4.0 is correct. 

### Steps to reproduce the bug

You can use this H2 example in the tutorial.

`cudaq.kernels.uccsd(kernel, qubits, params, nelec, qubits_num)`
`energy_of,data=cudaq.vqe(kernel,molecule,optimizer,tot_params)`

### Expected behavior

 Correcting it is essential to preserve the fermionic properties of the electrons. 

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 0.4.1
- **Python version**: 3.11
- **C++ compiler**: N/A
- **Operating system**: linux

### Suggestions

You should add the missing "Z" as in the equations above.

### PR DESCRIPTION
**Pull request by amccaskey**
UCCSD bug fixes, implementation adapted from @marwafar 

Fixes #952

### CODE REVIEW

**Review by bmhowe23 — COMMENTED** [review]
Do our chemistry interfaces need to remain stable? I.e., should the old function interfaces (`generateExcitations`, `singletExcitation`, `doubletExcitation`, `uccsd_num_parameters`, and `uccsd`) be retained and/or deprecated? We normally try to do that for other interfaces, but I'm not sure about this one.

**Comment by amccaskey** [comment]
> Do our chemistry interfaces need to remain stable? I.e., should the old function interfaces (`generateExcitations`, `singletExcitation`, `doubletExcitation`, `uccsd_num_parameters`, and `uccsd`) be retained and/or deprecated? We normally try to do that for other interfaces, but I'm not sure about this one.

No. These will ultimately be moved to library code that builds atop cuda-quantum outside of this repository. With this PR I'm simply fixing a bug so that users of the current code can still use it while the libraries are being implemented.

**Review by 1tnguyen — APPROVED** [review]
Looking good. Fixing a tricky bug in UCCSD 👍

File: unittests/domains/ChemistryTester.cpp [hunk 1]
```diff
@@ -14,21 +14,24 @@
...
-  EXPECT_EQ(1, doubles[0][1]);
-  EXPECT_EQ(2, doubles[0][2]);
-  EXPECT_EQ(3, doubles[0][3]);
+  std::size_t numElectrons = 2;
+  std::size_t numQubits = 4;
+
+  auto [singlesAlpha, singlesBeta, doublesMixed, doublesAlpha, doublesBeta] =
+      cudaq::get_uccsd_excitations(numElectrons, numQubits);
+  EXPECT_TRUE(doublesAlpha.empty());
+  EXPECT_TRUE(doublesBeta.empty());
```
Comment (1tnguyen) [inline unittests/domains/ChemistryTester.cpp:23]: Very minor: It'd be nice to have a test case for this (maybe with more spin orbitals and electrons).

File: runtime/cudaq/domains/chemistry/uccsd.h [hunk 2]
```diff
@@ -13,192 +13,621 @@
...
+/// @brief An excitation_list is a vector of lists of indices.
+using excitation_list = std::vector<std::vector<std::size_t>>;
+
+/// @brief UCCSD excitations for single and double excitations.
+struct excitations {
+  excitation_list singles_alpha;
+  excitation_list singles_beta;
+  excitation_list doubles_mixed;
+  excitation_list doubles_alpha;
+  excitation_list doubles_beta;
```
Comment (1tnguyen) [inline runtime/cudaq/domains/chemistry/uccsd.h:26]: Question only: is there a reason to split them out explicitly vs. just having `singles` and `doubles` lists?
For example, we need to write 3 identical for loops to handle double excitations.

File: unittests/domains/ChemistryTester.cpp (hunk 1 above)
Comment (marwafar) [reply unittests/domains/ChemistryTester.cpp:23]: I have done test for up to 10 electrons and 20 spin molecular orbitals for system like LiH, N2, and H2O and it works. I am happy to test it again.

File: runtime/cudaq/domains/chemistry/uccsd.h (hunk 2 above)
Comment (marwafar) [reply runtime/cudaq/domains/chemistry/uccsd.h:26]: They are not identical loops. But we can concatenate singles_alpha and singles_beta in singles and doubles_mixed, doubles_alpha, and doubles_beta into doubles. The reason I did this splitting because I want to further optimize the UCCSD quantum circuit for the restricted spin case. In restricted spin case,  alpha and beta electrons are identical and therefore singles_alpha equals singles_beta and doubles_alpha equals doubles_beta. However, this is not possible when you have the number of alpha electrons does not equal the number of beta electrons.

File: unittests/domains/ChemistryTester.cpp (hunk 1 above)
Comment (amccaskey) [reply unittests/domains/ChemistryTester.cpp:23]: Marwa has given me a 4 electron, 8 qubit case. I will add it here.

**Review by bmhowe23 — APPROVED** [review]
👍
