### PR TITLE
Fix compiler crash when processing empty region

### LINKED ISSUE #531: The nvq++ compiler crashes when compiling a function containing any empty blocks
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When compiling an empty block in a `__qpu__` function, the `nvq++` compiler crashes.

### Steps to reproduce the bug

Execute the example in the `docs/sphinx/examples/cpp/providers/ionq.cpp` file, except comment out the `x<cudaq::ctrl>(q[i], q[i + 1]);` line. An alternate method is to add an empty `{}` prior to the `for` loop.

When compiled with `--target ionq` or `--target quantinuum`, the compiler will crash with the following error:

```
root@docker-desktop:/workspaces/cuda-quantum# nvq++ --target ionq examples/cpp/providers/ionq.cpp 
cudaq-opt: /opt/llvm/include/llvm/ADT/ilist_iterator.h:138: reference llvm::ilist_iterator<llvm::ilist_detail::node_options<mlir::Block, true, false, void>, true, false>::operator*() const [OptionsT = llvm::ilist_detail::node_options<mlir::Block, true, false, void>, IsReverse = true, IsConst = false]: Assertion `!NodePtr->isKnownSentinel()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /usr/local/cudaq/bin/cudaq-opt --pass-pipeline=builtin.module(canonicalize,lambda-lifting,func.func(memtoreg{quantum=0}),canonicalize,apply-op-specialization,kernel-execution,aggressive-early-inlining,func.func(quake-add-metadata),device-code-loader{use-quake=1},func.func(unwind-lowering),expand-measurements,func.func(lower-to-cfg),canonicalize,cse) ionq.qke -o ionq.qke.o0mnEe
1.      MLIR Parser: custom op parser 'builtin.module'
2.      MLIR Parser: custom op parser 'func.func'
3.      MLIR Parser: custom op parser 'cc.scope'
4.      MLIR Parser: custom op parser 'cc.loop'
5.      MLIR Parser: custom op parser 'cc.scope'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  cudaq-opt 0x0000555d661c9258 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 40
1  cudaq-opt 0x0000555d661c724e llvm::sys::RunSignalHandlers() + 238
2  cudaq-opt 0x0000555d661c9a08
3  libc.so.6 0x00007f8f7704b520
4  libc.so.6 0x00007f8f7709fa7c pthread_kill + 300
5  libc.so.6 0x00007f8f7704b476 raise + 22
6  libc.so.6 0x00007f8f770317f3 abort + 211
7  libc.so.6 0x00007f8f7703171b
8  libc.so.6 0x00007f8f77042e96
9  cudaq-opt 0x0000555d656772ef
10 cudaq-opt 0x0000555d65677252
11 cudaq-opt 0x0000555d656771f5
12 cudaq-opt 0x0000555d656437ed
13 cudaq-opt 0x0000555d656437a0 cudaq::cc::ScopeOp::parse(mlir::OpAsmParser&, mlir::OperationState&) + 352
14 cudaq-opt 0x0000555d65c38fbb
15 cudaq-opt 0x0000555d65c43284
16 cudaq-opt 0x0000555d65c40dc1
17 cudaq-opt 0x0000555d65c3f389
18 cudaq-opt 0x0000555d65642562 cudaq::cc::LoopOp::parse(mlir::OpAsmParser&, mlir::OperationState&) + 578
19 cudaq-opt 0x0000555d65c38fbb
20 cudaq-opt 0x0000555d65c43284
21 cudaq-opt 0x0000555d65c40dc1
22 cudaq-opt 0x0000555d65c3f389
23 cudaq-opt 0x0000555d656436fe cudaq::cc::ScopeOp::parse(mlir::OpAsmParser&, mlir::OperationState&) + 190
24 cudaq-opt 0x0000555d65c38fbb
25 cudaq-opt 0x0000555d65c43284
26 cudaq-opt 0x0000555d65c40dc1
27 cudaq-opt 0x0000555d65c3f389
28 cudaq-opt 0x0000555d65c3f3cc
29 cudaq-opt 0x0000555d655abc16 mlir::function_interface_impl::parseFunctionOp(mlir::OpAsmParser&, mlir::OperationState&, bool, mlir::StringAttr, llvm::function_ref<mlir::Type (mlir::Builder&, llvm::ArrayRef<mlir::Type>, llvm::ArrayRef<mlir::Type>, mlir::function_interface_impl::VariadicFlag, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&)>, mlir::StringAttr, mlir::StringAttr) + 1750
30 cudaq-opt 0x0000555d64015e0a mlir::func::FuncOp::parse(mlir::OpAsmParser&, mlir::OperationState&) + 250
31 cudaq-opt 0x0000555d65c38fbb
32 cudaq-opt 0x0000555d65c43284
33 cudaq-opt 0x0000555d65c40dc1
34 cudaq-opt 0x0000555d65c3f389
35 cudaq-opt 0x0000555d655478a1 mlir::ModuleOp::parse(mlir::OpAsmParser&, mlir::OperationState&) + 161
36 cudaq-opt 0x0000555d65c38fbb
37 cudaq-opt 0x0000555d65c37558 mlir::parseAsmSourceFile(llvm::SourceMgr const&, mlir::Block*, mlir::ParserConfig const&, mlir::AsmParserState*, mlir::AsmParserCodeCompleteContext*) + 2296
38 cudaq-opt 0x0000555d65c254aa mlir::parseSourceFile(std::shared_ptr<llvm::SourceMgr> const&, mlir::Block*, mlir::ParserConfig const&, mlir::LocationAttr*) + 186
39 cudaq-opt 0x0000555d654e3cfe
40 cudaq-opt 0x0000555d654e345e
41 cudaq-opt 0x0000555d654e3218
42 cudaq-opt 0x0000555d660dd245 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, bool, bool) + 837
43 cudaq-opt 0x0000555d654e1482 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (mlir::PassManager&)>, mlir::DialectRegistry&, bool, bool, bool, bool, bool, bool, bool) + 306
44 cudaq-opt 0x0000555d654e19d5 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&, bool) + 1125
45 cudaq-opt 0x0000555d63c8c877 main + 583
46 libc.so.6 0x00007f8f77032d90
47 libc.so.6 0x00007f8f77032e40 __libc_start_main + 128
48 cudaq-opt 0x0000555d63c8c565 _start + 37
/usr/local/cudaq/bin/nvq++: line 22: 182000 Aborted                 $*
failed: "/usr/local/cudaq/bin/cudaq-opt --pass-pipeline=builtin.module(canonicalize,lambda-lifting,func.func(memtoreg{quantum=0}),canonicalize,apply-op-specialization,kernel-execution,aggressive-early-inlining,func.func(quake-add-metadata),device-code-loader{use-quake=1},func.func(unwind-lowering),expand-measurements,func.func(lower-to-cfg),canonicalize,cse) ionq.qke -o ionq.qke.o0mnEe"
```

The compiler does not crash when compiling with `--target nvidia` or with no `target` specified.

### Expected behavior

The compiler should not crash.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: latest commit on main branch: commit 26fe7e7
- **Python version**: N/A
- **C++ compiler**: ghcr.io/nvidia/cuda-quantum-devdeps:ext-llvm-main
- **Operating system**: ghcr.io/nvidia/cuda-quantum-devdeps:ext-llvm-main

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by bmhowe23**
Closes #531

### CODE REVIEW

File: lib/Optimizer/Dialect/CC/CCOps.cpp [hunk 1]
```diff
@@ -827,7 +827,7 @@ void cudaq::cc::ScopeOp::print(OpAsmPrinter &p) {
 static void ensureScopeRegionTerminator(OpBuilder &builder,
                                         OperationState &result,
                                         Region *region) {
-  auto *block = &region->back();
+  auto *block = region->empty() ? NULL : &region->back();
```
Comment (amccaskey) [inline lib/Optimizer/Dialect/CC/CCOps.cpp:830]: `NULL` -> `nullptr`
