### PR TITLE
PyASTBridge Fixes - Issues 1446-1451

### LINKED ISSUE #1446: Error handling with controlled gates in python
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When attempting to use x.ctrl, user errors can lead to incorrect behavior rather than an error being raised. In the example below, the x control qubits are ignored, and instead applied to the following Hadamard gate.

### Steps to reproduce the bug

```
import cudaq

@cudaq.kernel
def test_kernel(nQubits: int):
    qubits = cudaq.qvector(nQubits)
    x(qubits)
    # behavior is strange, applies h to 6 qubits now
    x.control(qubits[0], qubits[1])
    h(qubits)

print(cudaq.draw(test_kernel,4)) 
```

### Expected behavior

The above code should either throw an error (telling the user to use x.ctrl instead), or support x.control as an alias for x.ctrl.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

-Docker Image ID: 109eb1c12738

### Suggestions

_No response_

### LINKED ISSUE #1447: Error handling when acting ctrl on wrong data type
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

If the user uses the ctrl function incorrectly, no error is thrown, and no operation is done.

### Steps to reproduce the bug

```
import cudaq

@cudaq.kernel
def test_kernel(nQubits: int):
    qubits = cudaq.qvector(nQubits)
    x(qubits)
    # should throw error for acting on ints
    x.ctrl(0,1)

print(cudaq.draw(test_kernel,4))
```

### Expected behavior

In the example above, ints are passed into x.ctrl instead of qubits. The code runs without throwing any errors. The expected behavior would be that an error is thrown telling the user that ints are not a valid function argument for x.ctrl.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

-Docker Image ID: 109eb1c12738

### Suggestions

_No response_

### LINKED ISSUE #1448: IndexError when using math.pi inside kernel
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When attempting to use math.pi inside a kernel, the error
`IndexError: pop from an empty deque`
is returned.

### Steps to reproduce the bug

```
import math
import cudaq

@cudaq.kernel
def test_kernel():
    theta = math.pi

counts = cudaq.sample(test_kernel)
```

### Expected behavior

The expected behavior would be either to support math.pi, or to provide an error which explains that this is not allowed.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

-Docker Image ID: 109eb1c12738

### Suggestions

_No response_

### LINKED ISSUE #1449: Assertion error when attempting to use len()
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

`cudaq.qvector` supports the `.size()` function, but if the user mistakenly uses `len()` the error that is return is:
`AssertionError`
which is not enough to diagnose the problem.

### Steps to reproduce the bug

```
import cudaq

@cudaq.kernel
def test_kernel(nCountingQubits: int):
    qubits = cudaq.qvector(nCountingQubits)
    # N = counting_qubits.size()
    N = len(qubits)
    h(qubits)

nQubits = 4 
print(cudaq.draw(test_kernel, nQubits))
```

### Expected behavior

Expected behavior would be to either support `len()` as well as `.size()` or throw an error explaining that `len()` is not allowed.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

-Docker Image ID: 109eb1c12738

### Suggestions

_No response_

### LINKED ISSUE #1450: Error handling when missing parentheses
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

If the user forgets to add the parentheses to the cudaq.qubit constructor, the error:
`IndexError: pop from an empty deque`
is returned.

### Steps to reproduce the bug

```
import cudaq

@cudaq.kernel
def test_kernel():
    # state_reg = cudaq.qubit()
    state_reg = cudaq.qubit

    x(state_reg)

counts = cudaq.sample(test_kernel);
print(counts)
```

### Expected behavior

An error that helps identify the offending line of code.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

-Docker Image ID: 109eb1c12738

### Suggestions

_No response_

### LINKED ISSUE #1451: Error handling when passing float into int argument.
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When passing a float into the `range` function, the error that is returned does not mention `range` as the issue. The error that is returned is:
```
error: 'math.absi' op operand #0 must be signless-integer-like, but got 'f64'
RuntimeError: Failure while executing pass pipeline.

During handling of the above exception, another exception occurred:

RuntimeError: could not compile code for 'test_kernel'.
```

### Steps to reproduce the bug

```
import cudaq

@cudaq.kernel
def test_kernel(N: int):
    q = cudaq.qvector(N)
    # for i in range(0,int(N/2)):
    for i in range(0,N/2):
        swap(q[i], q[N-i-1])

N = 4 
print(cudaq.draw(test_kernel, N))
```

### Expected behavior

An error that identifies that `range` is the issue, as it is not clear from the user perspective where `math.absi` is coming from.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

-Docker Image ID: 109eb1c12738

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by amccaskey**
Fixes #1446 
Fixes #1447 
Fixes #1448 
Fixes #1449 
Fixes #1450 
Fixes #1451

### CODE REVIEW

File: runtime/cudaq/qis/managers/BasicExecutionManager.h [hunk 1]
```diff
@@ -110,14 +110,6 @@ class BasicExecutionManager : public cudaq::ExecutionManager {
     if (!executionContext)
       return;
 
-    if (isInTracerMode()) {
```
Comment (bmhowe23) [inline runtime/cudaq/qis/managers/BasicExecutionManager.h:113]: I believe this diff is from PR #1457, so presumably it will go away once that PR is merged?

File: python/tests/kernel/test_kernel_features.py [hunk 2]
```diff
@@ -988,3 +990,228 @@ def kernel(argument: float):
...
+    @cudaq.kernel
+    def test_kernel():
+        state_reg = cudaq.qubit
+        x(state_reg)
+    
+    with pytest.raises(RuntimeError) as e:
+        test_kernel.compile()
+    assert 'Invalid assignment detected.'
+
+# def test_cast_error_1451():
```
Comment (bmhowe23) [inline python/tests/kernel/test_kernel_features.py:1209]: Why is this new test for issue #1451 commented out?

File: python/tests/kernel/test_kernel_features.py [hunk 3]
```diff
@@ -988,3 +990,228 @@ def kernel(argument: float):
...
         print(cudaq.draw(kernel))
+
+
+def test_user_error_op_attr_1446():
+
+    @cudaq.kernel
+    def test_kernel(nQubits: int):
+        qubits = cudaq.qvector(nQubits)
+        x(qubits)
+        # behavior is strange, applies h to 6 qubits now
```
Comment (bmhowe23) [inline python/tests/kernel/test_kernel_features.py:1001]: We should probably remove this comment since this PR presumably fixes the issue described in the comment. (Same for lines 1014, 1027, and 1040.)

File: runtime/cudaq/qis/managers/BasicExecutionManager.h (hunk 1 above)
Comment (amccaskey) [reply runtime/cudaq/qis/managers/BasicExecutionManager.h:113]: Yea that's right. I just needed the change to keep the tests passing locally.

File: python/tests/kernel/test_kernel_features.py (hunk 2 above)
Comment (amccaskey) [reply python/tests/kernel/test_kernel_features.py:1209]: Whoops, oversight. Adding back in next commit.

File: python/tests/kernel/test_kernel_features.py (hunk 3 above)
Comment (amccaskey) [reply python/tests/kernel/test_kernel_features.py:1001]: I agree, will remove

**Review by bmhowe23 — APPROVED** [review]
+6
