### PR TITLE
Fix qreg/qspan deprecation warnings in build

### LINKED ISSUE #1025: Remove qreg use from kernel_builder.{h,cpp}
See https://github.com/NVIDIA/cuda-quantum/pull/1024/files for the changes.

This requires removing the calls to this interface as well.

### LINKED ISSUE #1026: Remove qreg use from qubit_qis.h
qreg is used in a concept in this header. Can the concept be deleted?

### PR DESCRIPTION
**Pull request by amccaskey**
Fix #1025 #1026. 

Also update `cudaq::range()` to support stop and step values #1028

### CODE REVIEW

File: runtime/cudaq/builder/kernel_builder.h [hunk 1]
```diff
@@ -10,7 +10,6 @@
 
 #include "cudaq/builder/QuakeValue.h"
 #include "cudaq/qis/modifiers.h"
-#include "cudaq/qis/qreg.h"
 #include "cudaq/qis/qvector.h"
 #include "cudaq/utils/cudaq_utils.h"
 #include "host_config.h"
```
Comment (schweitzpgi) [inline runtime/cudaq/builder/kernel_builder.h:15]: Can also removed lines 26-33.

Comment (amccaskey) [reply runtime/cudaq/builder/kernel_builder.h:15]: Ah yes, thanks.

File: runtime/cudaq/utils/cudaq_utils.h [hunk 2]
```diff
@@ -240,12 +240,30 @@ std::vector<double> random_vector(const double l_range, const double r_range,
...
-inline std::vector<std::size_t> range(int N) {
-  std::vector<std::size_t> vec(N);
-  std::iota(vec.begin(), vec.end(), 0);
+/// @brief Return a vector of integers. The first element is the
+/// user-specified `start` value. The remaining values are all values
+/// incremented by `step` (defaults to 1) until the `stop` value is reached
+/// (exclusive).
+template <typename ElementType>
+inline std::vector<ElementType> range(ElementType start, ElementType stop,
+                                      ElementType step = 1) {
```
Comment (schweitzpgi) [inline runtime/cudaq/utils/cudaq_utils.h:249]: Did you update the bridge for this? When I implemented this in the bridge I remember wondering about the default step value.

File: test/AST-Quake/passQregNToQSpan.cpp [hunk 3]
```diff
@@ -29,7 +29,7 @@ struct entry {
 // CHECK-LABEL:   func.func @__nvqpp__mlirgen__entry() attributes {
 // CHECK:           %[[VAL_1:.*]] = quake.alloca !quake.veq<3>
 // CHECK:           %[[VAL_2:.*]] = quake.relax_size %[[VAL_1]] : (!quake.veq<3>) -> !quake.veq<?>
-// CHECK:           call @__nvqpp__mlirgen__function_mcx._Z3mcxN5cudaq5qspan{{.*}}(%[[VAL_2]]) : (!quake.veq<?>) -> ()
+// CHECK:           call @__nvqpp__mlirgen__function_mcx._Z3mcxN5cudaq5{{.*}}(%[[VAL_2]]) : (!quake.veq<?>) -> ()
```
Comment (schweitzpgi) [inline test/AST-Quake/passQregNToQSpan.cpp:32]:
```suggestion
// CHECK:           call @__nvqpp__mlirgen__function_mcx._Z3mcxN5cudaq5qview{{.*}}(%[[VAL_2]]) : (!quake.veq<?>) -> ()
```
?

**Review by schweitzpgi — APPROVED** [review]
LGTM. Thanks, Alex, for helping drive the stake in this one.

File: runtime/cudaq/utils/cudaq_utils.h (hunk 2 above)
Comment (amccaskey) [reply runtime/cudaq/utils/cudaq_utils.h:249]: I did not. I thought I would leave that for a follow up. I'll add the ticket.

File: test/AST-Quake/passQregNToQSpan.cpp (hunk 3 above)
Comment (amccaskey) [reply test/AST-Quake/passQregNToQSpan.cpp:32]: I had that, but then I figured why not just slurp the qview up too. Ultimately I thought that keeping qview was just a test that Clang can mangle the function signature so I decided we didn't need to test that here.

Comment (schweitzpgi) [reply test/AST-Quake/passQregNToQSpan.cpp:32]: That's fine. I thought this might be trying to disambiguate the call from something else.

File: runtime/cudaq/qis/qubit_qis.h [hunk 4]
```diff
@@ -11,7 +11,6 @@
 #include "common/MeasureCounts.h"
 #include "cudaq/qis/modifiers.h"
 #include "cudaq/qis/qarray.h"
-#include "cudaq/qis/qreg.h"
```
Comment (bmhowe23) [inline runtime/cudaq/qis/qubit_qis.h:14]: I know this is already merged, but ...
While this particular change eliminates the warnings in our build, it will also break any user code that is using `qreg` (as evidenced by #1039), unless they specifically add this `#include` into their source code. So, as written, I think this is a breaking change. We may need to add additional documentation in the release notes that specifies that additional `#include`s are needed if the user wants to use `qreg` with our next release.

Comment (bmhowe23) [reply runtime/cudaq/qis/qubit_qis.h:14]: > I know this is already merged, but ... While this particular change eliminates the warnings in our build, it will also break any user code that is using `qreg` (as evidenced by #1039), unless they specifically add this `#include` into their source code. So, as written, I think this is a breaking change. We may need to add additional documentation in the release notes that specifies that additional `#include`s are needed if the user wants to use `qreg` with our next release. Another option would be to add this line back in before our 0.6 release.

#1042 contains a possible alternative to try to keep the best of both worlds. Let me know what you think.
