### PR TITLE
Only register MLIR dialect once at runtime

### LINKED ISSUE #2761: MLIR registration multiple times at runtime with mulithreading
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [x] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When trying to create many kernels in parallel, we accidentally try to register our MLIR dialect multiple times at runtime. 

### Steps to reproduce the bug

```
auto build_kernel() {
  auto kernel = cudaq::make_kernel();
  auto q = kernel.qalloc();
  kernel.x(q);
  return kernel;
}

TEST(testRepro, minimalRepro) {
#pragma omp parallel
  for (size_t idx = 0; idx < 10; ++idx) {
      auto kernel = build_kernel();
      auto result = cudaq::sample(kernel);
      auto now = std::chrono::system_clock::now();
      std::time_t time = std::chrono::system_clock::to_time_t(now);
      std::cout << std::ctime(&time);
  }

}
```

test: /home/.llvm-project/mlir/lib/Pass/PassRegistry.cpp:102: void mlir::registerPassPipeline(llvm::StringRef, llvm::StringRef, const PassRegistryFunction&, std::function<void(llvm::function_ref<void(const mlir::detail::PassOptions&)>)>): Assertion `inserted && "Pass pipeline registered multiple times"' failed.

### Expected behavior

We'd expect output like the following, which indicates all kernels were processed and executed in parallel

```
Wed Mar 26 19:20:46 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_367535629127() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:46 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_093606261879() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:46 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_202375922897() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:47 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_361293194784() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:47 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_503610632061() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:47 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_554765693745() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:47 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_254744307868() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:47 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_843149206892() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:47 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_664950487172() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}

Wed Mar 26 19:20:47 2025
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_722610615949() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %0 = quake.alloca !quake.ref
    quake.x %0 : (!quake.ref) -> ()
    return
  }
}
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA-Q version**: Latest
- **Python version**: 
- **C++ compiler**: 
- **Operating system**: 

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by anthony-santana**
### Description

Closes #2761

### CODE REVIEW

File: runtime/common/RuntimeMLIR.cpp [hunk 1]
```diff
@@ -71,17 +70,22 @@ TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(
 
 namespace cudaq {
 
+static std::once_flag mlir_init_flag;
+static bool mlirLLVMInitialized = false;
```
Comment (boschmitt) [inline runtime/common/RuntimeMLIR.cpp:74]: Do we still need the `mlirLLVMInitialized` flag ?

Comment (schweitzpgi) [reply runtime/common/RuntimeMLIR.cpp:74]: Please get rid of it.

**Review by 1tnguyen — APPROVED** [review]
LGTM 👍 Thanks, @anthony-santana.
