### PR TITLE
Checking for the build config status

### LINKED ISSUE #2410: `build_cudaq.sh` tries to build the project even if configuration fails.
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

 When trying to debug #2409, I noticed that the build script will try do build the project even if configuration fails:

```
-- Configuring incomplete, errors occurred!
Building CUDA-Q with configuration Release...
ninja: error: loading 'build.ninja': No such file or directory
Error: Build failed. Please check the console output or the files in the /workspace/build/logs directory.
```

### Steps to reproduce the bug

N/A

### Expected behavior

If configuration fails, there is not reason to try building the project.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA-Q version**: main (39a46e62ccc85922958925441c0e2e489eb27a83)

### Suggestions

Check if the configuration step was successful in here:
https://github.com/NVIDIA/cuda-quantum/blob/39a46e62ccc85922958925441c0e2e489eb27a83/scripts/build_cudaq.sh#L177-L194

### PR DESCRIPTION
**Pull request by sacpis**
Fixes #2410 

# Output

Tried setting CUQUANTUM_INSTALL_PREFIX to some invalid path

```
root@0a258c0dfa5e:/workspaces/cuda-quantum# bash scripts/build_cudaq.sh
CUDA version 12.0 detected.
No cuQuantum installation detected. Please set the environment variable CUQUANTUM_INSTALL_PREFIX to enable cuQuantum integration.
Some backends will be omitted from the build.
Using cuTensor installation in /usr/local/lib/python3.10/dist-packages/cutensor.
find: ‘/invalid/path’: No such file or directory
Preparing CUDA-Q build with LLVM installation in /invalid/path...
Error: CMake configuration failed. Please check logs/cmake_error.txt for details.
Skipping submodule 'tpls/llvm'
WARNING: Skipped stim_test target. `GTest` not found. To fix, follow Standalone CMake Project install instructions at https://github.com/google/googletest/blob/master/googletest/README.md
WARNING: Skipped stim_python_bindings target. `pybind11` not found. To fix, install pybind11. On debian based distributions, the package name is `pybind11-dev`
CMake Error at runtime/nvqir/custatevec/CMakeLists.txt:27 (message):
  

  Unable to find custatevec installation.  Please ensure it is correctly
  installed and set and define CUSTATEVEC_ROOT if necessary (currently set
  to: /invalid/path).
```

### CODE REVIEW

File: scripts/build_cudaq.sh [hunk 1]
```diff
@@ -176,9 +176,18 @@ cmake_args="-G Ninja '"$repo_root"' \
...
 else
   echo $cmake_args | xargs cmake \
     2> logs/cmake_error.txt 1> logs/cmake_output.txt
+  status=$?
+fi
+
+# Check if cmake succeeded
+if [ "$status" -ne 0 ]; then
+  echo -e "\e[01;31mError: CMake configuration failed. Please check logs/cmake_error.txt for details.\e[0m" >&2
+  cat logs/cmake_error.txt
```
Comment (schweitzpgi) [inline scripts/build_cudaq.sh:189]:
```suggestion
  cat logs/cmake_error.txt >&2
```
should this be the stderr as well?

**Review by schweitzpgi — APPROVED** [review]
+1
