### PR TITLE
Fix logical `&&` operator in `__qpu__` kernels

### LINKED ISSUE #810: Logical `&&` operator not working in `__qpu__` kernels
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

For a statement like `if (a && b) { doSomething(); }`, the generated IR is incorrect. This is the current behavior:
| a | b | Actual Result | Expected Result |
|---|---|---|---|
| false | false | true | false |
| false | true | true | false |
| true | false | false | false |
| true | true | true | true |

### Steps to reproduce the bug

With the following test.cpp file:
```cpp
#include <cudaq.h>

struct kernel {
  void operator()(bool a, bool b) __qpu__ {
    cudaq::qubit q;
    if (a && b)
      x(q);
    mz(q);
  }
};

int main() {

  int nShots = 100;
  // Sample
  auto counts = cudaq::sample(/*shots*/ nShots, kernel{}, false, false);
  counts.dump();
  counts = cudaq::sample(/*shots*/ nShots, kernel{}, false, true);
  counts.dump();
  counts = cudaq::sample(/*shots*/ nShots, kernel{}, true, false);
  counts.dump();
  counts = cudaq::sample(/*shots*/ nShots, kernel{}, true, true);
  counts.dump();
  return 0;
}
```
Run the following compile/run commands from the build directory (or adjust if you're running from another directory):
```bash
[root@docker-desktop build (main)]# bin/nvq++ ~/test.cpp --target quantinuum --emulate
[root@docker-desktop build (main)]# ./a.out 
{ 1:100 }
{ 1:100 }
{ 0:100 }
{ 1:100 }
```

### Expected behavior

It should follow the typical logical `&&` operator behavior as shown in the truth table in the bug description.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **Python version**: N/A
- **C++ compiler**: 16.0.6
- **Operating system**: Ubuntu 22.04

### Suggestions

A PR will be forthcoming with a fix.

### PR DESCRIPTION
**Pull request by bmhowe23**
Fixes #810.

### CODE REVIEW

File: test/AST-Quake/if.cpp [hunk 1]
```diff
@@ -65,3 +65,63 @@ struct kernel_else {
...
+  }
+};
+
+// CHECK-LABEL:   func.func @__nvqpp__mlirgen__kernel_short_circuit_and() -> i32 attributes {"cudaq-entrypoint", "cudaq-kernel"} {
+// CHECK:           %[[VAL_0:.*]] = arith.constant false
+// CHECK:           %[[VAL_1:.*]] = arith.constant 0 : i32
+// CHECK:           %[[VAL_2:.*]] = quake.alloca !quake.veq<3>
+// CHECK:           %[[VAL_3:.*]] = quake.extract_ref %[[VAL_2]][0] : (!quake.veq<3>) -> !quake.ref
+// CHECK:           %[[VAL_4:.*]] = quake.mz %[[VAL_3]] : (!quake.ref) -> i1
+// CHECK:           %[[VAL_5:.*]] = arith.cmpi eq, %[[VAL_4]], %[[VAL_0]] : i1
```
Comment (schweitzpgi) [inline test/AST-Quake/if.cpp:84]: The `bool` comparison seemed like it might be avoided, since we're dealing with `bool`s in the first place. However, I can see where it makes both the `&&` and `||` cases follow a similar structure as well.

**Review by schweitzpgi — APPROVED** [review]
+1
