### PR TITLE
Fix Pauli word conversion bug in `observe_async`

### LINKED ISSUE #1566: Cannot pass a list of Pauli words to `observe_async`
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Passing a list of Pauli words to a `cudaq.observe_async()` function produces the following error:
```
RuntimeError: Unable to cast Python instance of type <class 'str'> to C++ type 'cudaq::pauli_word'
```

It works fine if you pass to `cudaq.observe()`.

### Steps to reproduce the bug

You can reproduce the bug by create a file called test.py with the following:
```python
import cudaq
import numpy as np
import random

random.seed(13)
np.random.seed(13)

def generateRandomPauliStrings(numQubits, numPaulis):
    s = ['X', 'Y', 'Z', 'I']
    return [
        ''.join([random.choice(s)
                for i in range(numQubits)])
        for i in range(numPaulis)
    ]

def build_cudaq_obs(hs, paulis):
    observable = cudaq.SpinOperator()
    for h, p in zip(hs, paulis):
        observable += h * cudaq.SpinOperator.from_word(p)
    return observable - cudaq.SpinOperator()


@cudaq.kernel
def gqeCirc(N: int, thetas: list[float], paulis: list[cudaq.pauli_word]):
    q = cudaq.qvector(N)
    for i in range(len(paulis)):
        exp_pauli(thetas[i], q, paulis[i])

numQubits = 4
numPaulis = 8
numberOfTerms = 4

# Generate the observable
obs_ps = generateRandomPauliStrings(numQubits, numberOfTerms)
obs = build_cudaq_obs([1.0]*len(obs_ps), obs_ps)

pauliStings = generateRandomPauliStrings(numQubits, numPaulis)
ts = np.random.rand(len(pauliStings))

exp_val = cudaq.observe_async(gqeCirc, obs, numQubits, list(ts), pauliStings).get().expectation()
print(exp_val)
```
When run, it produces this error:
```bash
$ python3 test2.py 
RuntimeError: Unable to cast Python instance of type <class 'str'> to C++ type 'cudaq::pauli_word'
```

### Expected behavior

It should run without errors

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: latest (bf579701d)
- **Python version**: 
- **C++ compiler**: 
- **Operating system**: 

### Suggestions

PR forthcoming

### PR DESCRIPTION
**Pull request by bmhowe23**
Fixes #1566

### CODE REVIEW

**Review by schweitzpgi — COMMENTED** [review]
LGTM

File: python/utils/OpaqueArguments.h [hunk 1]
```diff
@@ -155,22 +155,22 @@ inline py::args simplifiedValidateInputArguments(py::args &args) {
         throw std::runtime_error("Cannot pass ndarray with shape != (N,).");
 
       arg = args[i].attr("tolist")();
+    } else if (py::isinstance<py::str>(arg)) {
+      arg = cudaq::pauli_word(py::cast<std::string>(arg));
```
Comment (amccaskey) [inline python/utils/OpaqueArguments.h:159]: If you do it this way you may be able to remove the casting behavior from kernel_decorator

Comment (bmhowe23) [reply python/utils/OpaqueArguments.h:159]: > If you do it this way you may be able to remove the casting behavior from kernel_decorator

Hmm, removing that code seems to cause errors in `python/tests/kernel/test_kernel_features.py::test_pauli_word_input`:
```
RuntimeError: error: Can not handle conversion of python type <class 'str'> to MLIR type.
```

**Review by amccaskey — APPROVED** [review]
