### PR TITLE
Fix cudaq.exp_pauli usage of pauli_word for quantum devices

### LINKED ISSUE #2671: Bug in cudaq.exp_pauli for quantum devices (Python)
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

This is similar to https://github.com/NVIDIA/cuda-quantum/issues/2222

There are still some `exp_pauli` use cases in Python that do not lower to quantum hardware correctly.

### Steps to reproduce the bug

Use the [`python/tests/kernel/test_kernel_exp_pauli.py`](https://github.com/NVIDIA/cuda-quantum/blob/main/python/tests/kernel/test_kernel_exp_pauli.py) file in the repo ... add the following statements to the bottom of it.

```python
cudaq.set_target('quantinuum', emulate=True)
# This works
test_exp_pauli()
print('test_exp_pauli works')
# This fails
test_exp_pauli_param()
print('never gets here')
```

When run like the following, it produces this error:
```bash
$ python3 python/tests/kernel/test_kernel_exp_pauli.py
test_exp_pauli works
error: 'quake.exp_pauli' op cannot determine pauli word string
error: failed to legalize operation 'quake.exp_pauli'
RuntimeError: Remote rest platform Quake lowering failed.
```

### Expected behavior

Lowering to quantum hardware should work just like the simulation use case.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA-Q version**: latest (22ffd96d9 as of the time of this writing)
- **Python version**: 3.10
- **C++ compiler**: N/A
- **Operating system**: 

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by bmhowe23**
Fixes #2671

### CODE REVIEW

File: lib/Optimizer/Transforms/DecompositionPatterns.cpp [hunk 1]
```diff
@@ -340,6 +340,7 @@ struct ExpPauliDecomposition : public OpRewritePattern<quake::ExpPauliOp> {
     auto theta = expPauliOp.getParameter();
     auto pauliWord = expPauliOp.getPauli();
     auto stringTy = pauliWord.getType();
+    SmallVector<char> pauliWordAsVec;
```
Comment (schweitzpgi) [inline lib/Optimizer/Transforms/DecompositionPatterns.cpp:343]: Why not use a std::string here?

Comment (bmhowe23) [reply lib/Optimizer/Transforms/DecompositionPatterns.cpp:343]: My thinking was that the LLVM data structures were preferred in the compiler code, especially since `SmallVector`s might be more optimized for use cases like this. Let me know if you want me to change it.

**Review by annagrin — APPROVED** [review]
LGTM with a small comment

File: python/tests/kernel/test_kernel_exp_pauli.py [hunk 2]
```diff
@@ -7,9 +7,16 @@
 # ============================================================================ #
 
 import cudaq
+import pytest
 
 
-def test_exp_pauli():
+@pytest.mark.parametrize("target", ['qpp-cpu', 'quantinuum'])
```
[the remark this answers is not in the document]
Comment (bmhowe23) [reply python/tests/kernel/test_kernel_exp_pauli.py:13]: I made that parametrized test before I knew about the test in the backends directory, so I can back out this quantinuum test here.

[the remark this answers is not in the document]
Comment (bmhowe23) [reply python/tests/kernel/test_kernel_exp_pauli.py]: Removed in a71939adf

File: lib/Optimizer/Transforms/DecompositionPatterns.cpp (hunk 1 above)
Comment (bmhowe23) [reply lib/Optimizer/Transforms/DecompositionPatterns.cpp]: Changed in a71939adf
