### PR TITLE
Fix #276: Use regex to parse config file

### LINKED ISSUE #276: Platform config files cannot handle passes with options
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Currently, our platform specific configurations are defined as scripts, e.g. [quantinuum](https://github.com/NVIDIA/cuda-quantum/blob/main/runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.config). These files can define a specific pass pipeline using the `PLATFORM_LOWERING_CONFIG` variable. However, the use of pass options breaks the JIT compilation of kernels.

The problem is that the `RemoteRESTQPU` class will parse this file and split the line with this variable on `=`:
https://github.com/NVIDIA/cuda-quantum/blob/8147bf7a1012ef79eb56e9de96dbf3e1c3e71a8f/runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp#L215-L218

Since a pass with an option will have the form `pass-name{option=value}` this breaks the pipeline too.

### Steps to reproduce the bug

Add a pass with an option to the `PLATFORM_LOWERING_CONFIG` variable.

### Expected behavior

We need to be able to accept pass with options.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main-branch
- **C++ compiler**: gcc-12
- **Operating system**: Ubuntu (aarch64)

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by boschmitt**
### Description
Slightly more robust solution to parse target config scripts. We must re-address this when we refactor the driver.

### CODE REVIEW

**Review by amccaskey — APPROVED** [review]

File: runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp [hunk 1]
```diff
@@ -211,15 +208,15 @@ class RemoteRESTQPU : public cudaq::QPU {
...
-    for (auto &line : lines) {
-      if (line.find(platformLoweringConfig) != std::string::npos) {
-        auto keyVal = cudaq::split(line, '=');
-        auto value = std::regex_replace(keyVal[1], std::regex("\""), "");
-        cudaq::info("Appending lowering pipeline: {}", value);
-        passPipelineConfig += "," + value;
-      } else if (line.find(codeEmissionType) != std::string::npos) {
-        auto keyVal = cudaq::split(line, '=');
-        codegenTranslation = keyVal[1];
+    std::regex pipeline("PLATFORM_LOWERING_CONFIG\\s*=\\s*\"(\\S+)\"");
```
Comment (schweitzpgi) [inline runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp:211]:
```suggestion
    std::regex pipeline("PLATFORM_LOWERING_CONFIG\\s*=\\s*\"([^\"]*)\"");
```
Since this is quoted, it seems like it could be empty or contain whitespace.

**Comment by schweitzpgi** [comment]
Won't this match config lines that are commented out?

**Comment by schweitzpgi** [comment]
It could be more robust to have the options passed in as command line arguments or environment variables rather than trying to reparse the configuration file.

File: runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp (hunk 1 above)
Comment (boschmitt) [reply runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp:211]: Yes, but in either case there would be nothing to add to the pipeline, so I failure to match has the same effect.

**Comment by boschmitt** [comment]
> Won't this match config lines that are commented out?

It will indeed. I can adjust the regex. 

> It could be more robust to have the options passed in as command line arguments or environment variables rather than trying to reparse the configuration file.

Actually this is what I thought that was happening from the beginning. Since I'm unsure if other parts of the runtime are relying on parsing this file, I went to with trying to fix it by changing overall behavior as little as possible.
