### PR TITLE
Make C++ ASTBridge specification adherent for operation broadcasting 

### LINKED ISSUE #805: [QIR] Bug in lowering multi-ctrl to LLVM
```cpp 
#include "cudaq.h"

__qpu__ void fancyCnot(cudaq::qubit& a, cudaq::qubit& b) {
    x<cudaq::ctrl>(a,b);
}

__qpu__ void toffoli() {
    cudaq::qreg q(3);
    auto& ctrl = q.front();
    x(ctrl, q[2]);
    cudaq::control(fancyCnot, {ctrl}, q[1], q[2]);
}

int main() {
    toffoli();
}
```
will produce the following Quake after apply ops are specialized 
```mlir 
module attributes {quake.mangled_name_map = {__nvqpp__mlirgen__function_fancyCnot._Z9fancyCnotRN5cudaq5quditILm2EEES2_ = "_Z9fancyCnotRN5cudaq5quditILm2EEES2_", __nvqpp__mlirgen__function_toffoli._Z7toffoliv = "_Z7toffoliv"}} {
  func.func private @__nvqpp__mlirgen__function_fancyCnot._Z9fancyCnotRN5cudaq5quditILm2EEES2_.ctrl(%arg0: !quake.veq<?>, %arg1: !quake.ref, %arg2: !quake.ref) {
    quake.x [%arg0, %arg1] %arg2 : (!quake.veq<?>, !quake.ref, !quake.ref) -> ()
    return
  }
  func.func @__nvqpp__mlirgen__function_fancyCnot._Z9fancyCnotRN5cudaq5quditILm2EEES2_(%arg0: !quake.ref, %arg1: !quake.ref) attributes {"cudaq-kernel", no_this} {
    quake.x [%arg0] %arg1 : (!quake.ref, !quake.ref) -> ()
    return
  }
  func.func @__nvqpp__mlirgen__function_toffoli._Z7toffoliv() attributes {"cudaq-entrypoint", "cudaq-kernel", no_this} {
    %0 = quake.alloca !quake.veq<3>
    %1 = quake.extract_ref %0[0] : (!quake.veq<3>) -> !quake.ref
    %2 = quake.extract_ref %0[2] : (!quake.veq<3>) -> !quake.ref
    quake.x [%1] %2 : (!quake.ref, !quake.ref) -> ()
    %3 = quake.extract_ref %0[1] : (!quake.veq<3>) -> !quake.ref
    %4 = quake.extract_ref %0[2] : (!quake.veq<3>) -> !quake.ref
    %5 = quake.concat %1 : (!quake.ref) -> !quake.veq<?>
    call @__nvqpp__mlirgen__function_fancyCnot._Z9fancyCnotRN5cudaq5quditILm2EEES2_.ctrl(%5, %3, %4) : (!quake.veq<?>, !quake.ref, !quake.ref) -> ()
    return
  }
}
```
and the following LLVM
```llvm
; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%Array = type opaque
%Qubit = type opaque

declare void @__quantum__rt__qubit_release_array(%Array*) local_unnamed_addr

declare %Array* @__quantum__rt__array_create_1d(i32, i64) local_unnamed_addr

declare i8* @__quantum__rt__array_get_element_ptr_1d(%Array*, i64) local_unnamed_addr

declare %Array* @__quantum__rt__qubit_allocate_array(i64) local_unnamed_addr

declare void @invokeWithControlQubits(i64, void (%Array*, %Qubit*)*, ...) local_unnamed_addr

declare void @__quantum__qis__x__ctl(%Array*, %Qubit*)

define void @__nvqpp__mlirgen__function_fancyCnot._Z9fancyCnotRN5cudaq5quditILm2EEES2_(%Qubit* %0, %Qubit* %1) local_unnamed_addr {
  tail call void (i64, void (%Array*, %Qubit*)*, ...) @invokeWithControlQubits(i64 1, void (%Array*, %Qubit*)* nonnull @__quantum__qis__x__ctl, %Qubit* %0, %Qubit* %1)
  ret void
}

define void @__nvqpp__mlirgen__function_toffoli._Z7toffoliv() local_unnamed_addr {
  %1 = tail call %Array* @__quantum__rt__qubit_allocate_array(i64 3)
  %2 = tail call i8* @__quantum__rt__array_get_element_ptr_1d(%Array* %1, i64 0)
  %3 = bitcast i8* %2 to %Qubit**
  %4 = load %Qubit*, %Qubit** %3, align 8
  %5 = tail call i8* @__quantum__rt__array_get_element_ptr_1d(%Array* %1, i64 2)
  %6 = bitcast i8* %5 to %Qubit**
  %7 = load %Qubit*, %Qubit** %6, align 8
  tail call void (i64, void (%Array*, %Qubit*)*, ...) @invokeWithControlQubits(i64 1, void (%Array*, %Qubit*)* nonnull @__quantum__qis__x__ctl, %Qubit* %4, %Qubit* %7)
  %8 = tail call i8* @__quantum__rt__array_get_element_ptr_1d(%Array* %1, i64 1)
  %9 = bitcast i8* %8 to %Qubit**
  %10 = load %Qubit*, %Qubit** %9, align 8
  %11 = tail call %Array* @__quantum__rt__array_create_1d(i32 8, i64 1)
  %12 = tail call i8* @__quantum__rt__array_get_element_ptr_1d(%Array* %11, i64 0)
  %13 = bitcast i8* %12 to %Qubit**
  store %Qubit* %4, %Qubit** %13, align 8
  tail call void (i64, void (%Array*, %Qubit*)*, ...) @invokeWithControlQubits(i64 2, void (%Array*, %Qubit*)* nonnull @__quantum__qis__x__ctl, %Array* %11, %Qubit* %10, %Qubit* %7)
  tail call void @__quantum__rt__qubit_release_array(%Array* %1)
  ret void
}

!llvm.module.flags = !{!0}

!0 = !{i32 2, !"Debug Info Version", i32 3}
```

If we run this we'll get a bad value for the first control qubit on the multi-control operation 
```bash
[2023-10-20 18:53:52.766] [info] [PluginUtils.h:23] Requesting N5cudaq16quantum_platformE plugin via symbol name getQuantumPlatform.
[2023-10-20 18:53:52.766] [info] [PluginUtils.h:35] Successfully loaded the plugin.
[2023-10-20 18:53:52.766] [info] [PluginUtils.h:23] Requesting N5nvqir16CircuitSimulatorE plugin via symbol name getCircuitSimulator.
[2023-10-20 18:53:52.766] [info] [PluginUtils.h:35] Successfully loaded the plugin.
[2023-10-20 18:53:52.766] [info] [NVQIR.cpp:80] Creating the qpp backend.
[2023-10-20 18:53:52.766] [info] [CircuitSimulator.h:704] Allocating 3 new qubits.
[2023-10-20 18:53:52.766] [info] [CircuitSimulator.h:902] (apply) ctrl-x(0, 2)
[2023-10-20 18:53:52.766] [info] [CircuitSimulator.h:902] (apply) ctrl-x(94197222735880, 1, 2)
[2023-10-20 18:53:52.766] [info] [CircuitSimulator.h:729] Deallocating qubit 0
terminate called after throwing an instance of 'qpp::exception::SubsysMismatchDims'
  what():  qpp::applyCTRL(): Subsystems mismatch dimensions! [ctrl/dims]
Aborted (core dumped)
```

I think this is due to `invokeWithControlQubits` expecting only `Qubit*` arguments, yet we are passing an `Array*` as the first argument of the variadic args to that function.

### PR DESCRIPTION
**Pull request by amccaskey**
This PR fixes a bug in the C++ ASTBridge whereby `QuantumOp(qubit...), sizeof...(qubit) > 1` was treated as a controlled operation when it should be treated as a `QuantumOp` applied to all qubits in the variadic argument list. #875 

This PR also fixes the issues raised in #805 and #867, whereby control operations with multiple control operands of differing type (`veq` and `ref`) were not lowered to LLVM correctly.

### CODE REVIEW

File: lib/Optimizer/CodeGen/LowerToQIR.cpp [hunk 1]
```diff
@@ -441,24 +441,66 @@ class OneTargetRewrite : public ConvertOpToLLVMPattern<OP> {
...
-            parentModule, true);
-
+    // Check if all controls are qubit types, if so
+    // retain existing functionality
+    auto allControlsAreQubits = [&](auto controls) {
+      for (auto c : controls)
+        if (c.getType() != qirQubitPointerType)
+          return false;
+      return true;
+    }(adaptor.getControls());
```
Comment (bmhowe23) [inline lib/Optimizer/CodeGen/LowerToQIR.cpp:451]: For my own benefit, why are we passing in `adaptor.getControls()` when we're already capturing everything by reference? It seems like this would be adding an extra copy (but maybe the compiler is smart enough to get rid of it).

File: lib/Optimizer/CodeGen/LowerToQIR.cpp [hunk 2]
```diff
@@ -507,13 +549,12 @@ class OneTargetOneParamRewrite : public ConvertOpToLLVMPattern<OP> {
     auto loc = instOp.getLoc();
     ModuleOp parentModule = instOp->template getParentOfType<ModuleOp>();
     auto context = parentModule->getContext();
-    auto qirFunctionName = std::string(cudaq::opt::QIRQISPrefix) + instName;
+    auto qirQisPrefix = std::string(cudaq::opt::QIRQISPrefix);
```
Comment (bmhowe23) [inline lib/Optimizer/CodeGen/LowerToQIR.cpp:552]: I think @schweitzpgi has been encouraging the use of `llvm::StringRef` and `llvm::Twine` in the compiler. Can `llvm::Twine` be used here?

File: lib/Optimizer/CodeGen/LowerToQIR.cpp [hunk 3]
```diff
@@ -586,94 +608,76 @@ class OneTargetOneParamRewrite : public ConvertOpToLLVMPattern<OP> {
...
+
+      // Here we already have and Array*, Qubit*
+      rewriter.replaceOpWithNewOp<LLVM::CallOp>(instOp, TypeRange{},
+                                                instSymbolRef, funcArgs);
+      return success();
     }
 
-    // This is a single target op, add that type
-    tmpArgTypes.push_back(qubitIndexType);
+    // The remaining scenaries are best handled with the
```
Comment (bmhowe23) [inline lib/Optimizer/CodeGen/LowerToQIR.cpp:621]:
```suggestion
    // The remaining scenarios are best handled with the
```

File: unittests/integration/builder_tester.cpp [hunk 4]
```diff
@@ -972,6 +972,121 @@ CUDAQ_TEST(BuilderTester, checkExpPauli) {
...
+    kernel.x(control3);
+
+    kernel.ry<cudaq::ctrl>(M_PI_2, controls1, controls2, control3, target);
+
+    auto counts = cudaq::sample(kernel);
+    counts.dump();
+
+    // Target qubit should have a 50/50 mix between |0> and |1>
+    EXPECT_EQ(counts.count("111111"), 505);
+    EXPECT_EQ(counts.count("111110"), 495);
```
Comment (bmhowe23) [inline unittests/integration/builder_tester.cpp:1066]: Did you want to update this to use `EXPECT_TRUE` like you updated unittests/backends/quantinuum/QuantinuumTester.cpp? (They're both setting the random seed, so I'm ok either way ... just figured I'd double check.)

File: include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h [hunk 5]
```diff
@@ -29,6 +29,8 @@ constexpr static const char NVQIRInvokeWithControlBits[] =
     "invokeWithControlQubits";
 constexpr static const char NVQIRInvokeRotationWithControlBits[] =
     "invokeRotationWithControlQubits";
+constexpr static const char NVQIRInvokeWithControlRegisterOrBits[] =
+    "invokeWithControlRegisterOrQubits";
```
Comment (bmhowe23) [inline include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h:33]: Will this new function ever end up in the Base Profile or Adaptive Profile QIR? I'm thinking it won't because I believe multi-control decomposition would've eliminated all of these, but I figured I'd double check.

**Review by bmhowe23 — APPROVED** [review]
I suspect we should probably add the "Breaking Change" label because the compiler's interpretation of `x(q0, q1)` is changing with this PR. (I agree it's a good bug fix because it was previously not compliant with the language specification.)

Just a few additional comments below.

**Comment by bettinaheim** [comment]
> I suspect we should probably add the "Breaking Change" label because the compiler's interpretation of `x(q0, q1)` is changing with this PR. (I agree it's a good bug fix because it was previously not compliant with the language specification.)
> 
> Just a few additional comments below.

@amccaskey Could you please update the PR description to clearly describe what the change in behavior is and briefly why it was changed (to fix the issues), so that someone who is using CUDA Quantum for application development will understand it, and understand how they need to change their code.

File: lib/Optimizer/Builder/Factory.cpp [hunk 6]
```diff
@@ -7,13 +7,52 @@
...
+  auto i64Type = rewriter.getI64Type();
+  auto context = rewriter.getContext();
+  Value isArrayAndLengthArr = rewriter.create<LLVM::AllocaOp>(
+      loc, LLVM::LLVMPointerType::get(i64Type), numOperands);
+  auto intPtrTy = LLVM::LLVMPointerType::get(i64Type);
+  Value zero = rewriter.create<arith::ConstantIntOp>(loc, 0, 64);
+  auto getSizeSymbolRef = cudaq::opt::factory::createLLVMFunctionSymbol(
+      cudaq::opt::QIRArrayGetSize, i64Type, {cudaq::opt::getArrayType(context)},
+      parentModule);
+  for (std::size_t i = 0; auto controlOperand : operands) {
```
Comment (schweitzpgi) [inline lib/Optimizer/Builder/Factory.cpp:36]: nit: it looks like you can use `llvm::enumerate` here.

File: lib/Optimizer/CodeGen/LowerToQIR.cpp (hunk 2 above)
Comment (schweitzpgi) [reply lib/Optimizer/CodeGen/LowerToQIR.cpp:552]:
```suggestion
    std::string qirQisPrefix = cudaq::opt::QIRQISPrefix;
```
`llvm::Twine` is a foot gun to only be brought out of the box on very special holidays ... more specifically, it is _sometimes_ ok to use it to pass in a single argument that is capable of assembling a string in the called function because none of the parts to be assembled have vanished yet.

File: include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h (hunk 5 above)
Comment (amccaskey) [reply include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h:33]: You're right, it should not due to the multi-control decomp pass.

File: lib/Optimizer/CodeGen/LowerToQIR.cpp (hunk 1 above)
Comment (amccaskey) [reply lib/Optimizer/CodeGen/LowerToQIR.cpp:451]: I think you are right. I can just drop the lambda argument here and use adaptor directly.

**Comment by amccaskey** [comment]
> > I suspect we should probably add the "Breaking Change" label because the compiler's interpretation of `x(q0, q1)` is changing with this PR. (I agree it's a good bug fix because it was previously not compliant with the language specification.)
> > Just a few additional comments below.
> 
> @amccaskey Could you please update the PR description to clearly describe what the change in behavior is and briefly why it was changed (to fix the issues), so that someone who is using CUDA Quantum for application development will understand it, and understand how they need to change their code.

@bettinaheim Updated the PR title and description. Let me know if you need more than that.

**Review by schweitzpgi — APPROVED** [review]
It's going to be great.

**Comment by bettinaheim** [comment]
> > > I suspect we should probably add the "Breaking Change" label because the compiler's interpretation of `x(q0, q1)` is changing with this PR. (I agree it's a good bug fix because it was previously not compliant with the language specification.)
> > > Just a few additional comments below.
> > 
> > 
> > @amccaskey Could you please update the PR description to clearly describe what the change in behavior is and briefly why it was changed (to fix the issues), so that someone who is using CUDA Quantum for application development will understand it, and understand how they need to change their code.
> 
> @bettinaheim Updated the PR title and description. Let me know if you need more than that.

@amccaskey I updated the description in the PR that is linked in the release notes to give a concrete example of what behavior remains the same, vs what behavior changes:

https://github.com/NVIDIA/cuda-quantum/pull/898

**Comment by anthony-santana** [comment]
There are some builder gate overloads, such as ([for standard x,y,z,etc. gates](https://github.com/NVIDIA/cuda-quantum/blob/d69a01bf0a670294d59d79f87583513f29f80bd2/runtime/cudaq/builder/kernel_builder.h#L436))

```
  void NAME(std::vector<QuakeValue> &ctrls, QuakeValue &target) {              
    details::NAME(*opBuilder, ctrls, target);                                  
  }                                                                            
```

and for [rotation gates](https://github.com/NVIDIA/cuda-quantum/blob/d69a01bf0a670294d59d79f87583513f29f80bd2/runtime/cudaq/builder/kernel_builder.h#L476)
```
  void NAME(QuakeValue parameter, std::vector<QuakeValue> &ctrls,          
            QuakeValue &target) {
             ...
  }                                                                            
  void NAME(double parameter, std::vector<QuakeValue> &ctrls,                 
            QuakeValue &target) {
             ...         
  }                                                                          
```

These allow for the following builder kernels, which as I understand, now deviate from the nvq++ behavior
```
  {
    auto kernel = cudaq::make_kernel();
    std::vector<cudaq::QuakeValue> ctrls{kernel.qalloc(), kernel.qalloc()};
    auto target = kernel.qalloc();
    
    // No cudaq::ctrl annotation needed
    kernel.x(ctrls, target);
    kernel.rx(1.1, ctrls, target);

    auto result = cudaq::sample(kernel);
    result.dump();
  }

```
