### PR TITLE
Fix #2863.

### LINKED ISSUE #2863: Wrong handling of `u3`'s adjoint
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

@amccaskey found the issue.

The adjoint of `U3` is not only the negation of its parameters. On top of negating the parameters, on must also swap the last two. Using CUDA-Q's parameter ordering for `U3` the following should hold:

```
u3<adj>(a, b, c) != u3(-a, -b, -c)

# The adjoint is:
u3<adj>(a, b, c) == u3(-a, -c, -b)
```

### Steps to reproduce the bug

The following test shouldn't be passing:

https://github.com/NVIDIA/cuda-quantum/blob/b9e780db1be6a818502b8f95bf799caefbe7d1ab/unittests/qis/QubitQISTester.cpp#L419-L436

The `u3` mimicking `rx` should be (the minus sign on the second parameter):
```c++
     u3(1.1, -M_PI_2, M_PI_2, q); 
     // rx<adj>(angle) = u3<adj>(angle, -pi/2, pi/2) 
     u3<cudaq::adj>(1.1, -M_PI_2, M_PI_2, q); 
```

Fixing the test case for the correct code makes it not pass, thus we must be handling the `u3`'s adjoint wrong in the compiler and/or in the simulators. 

These are a couple of places in the code base where the adjoint of `u3` might be mishandled (Only negating the parameters):

https://github.com/NVIDIA/cuda-quantum/blob/b9e780db1be6a818502b8f95bf799caefbe7d1ab/lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp#L1299-L1304

https://github.com/NVIDIA/cuda-quantum/blob/b9e780db1be6a818502b8f95bf799caefbe7d1ab/lib/Optimizer/Transforms/DecompositionPatterns.cpp#L1605-L1609

### Expected behavior

Correctly handling the adjoint of `u3` 

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA-Q version**: main (b9e780db1be6a818502b8f95bf799caefbe7d1ab)

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by schweitzpgi**
Fix bugs with the u3<adj> operator.

### CODE REVIEW

File: unittests/qis/QubitQISTester.cpp [hunk 1]
```diff
@@ -422,7 +422,7 @@ CUDAQ_TEST(QubitQISTester, checkU3Adj) {
     // mimic Rx gate
     u3(1.1, -M_PI_2, M_PI_2, q);
     // rx<adj>(angle) = u3<adj>(angle, pi/2, -pi/2)
-    u3<cudaq::adj>(1.1, M_PI_2, -M_PI_2, q);
+    u3<cudaq::adj>(1.1, -M_PI_2, M_PI_2, q);
```
Comment (khalatepradnya) [inline unittests/qis/QubitQISTester.cpp:425]: There's a Python counterpart to this test - https://github.com/NVIDIA/cuda-quantum/blob/main/python/tests/kernel/test_kernel_features.py#L1513 which should also be updated similarly.

Comment (schweitzpgi) [reply unittests/qis/QubitQISTester.cpp:425]: See 471f0b85

File: unittests/qis/QubitQISTester.cpp [hunk 2]
```diff
@@ -422,7 +422,7 @@ CUDAQ_TEST(QubitQISTester, checkU3Adj) {
     // mimic Rx gate
     u3(1.1, -M_PI_2, M_PI_2, q);
     // rx<adj>(angle) = u3<adj>(angle, pi/2, -pi/2)
```
Comment (boschmitt) [inline unittests/qis/QubitQISTester.cpp:424]:
```suggestion
    // rx<adj>(angle) = u3<adj>(angle, -pi/2, pi/2)
```

File: python/tests/kernel/test_kernel_features.py [hunk 3]
```diff
@@ -1519,7 +1519,7 @@ def rotation_adjoint_test():
         # implement Rx gate with U3
         u3(1.1, -np.pi / 2, np.pi / 2, q)
         # rx.adj(angle) = u3.adj(angle, pi/2, -pi/2)
```
Comment (boschmitt) [inline python/tests/kernel/test_kernel_features.py:1521]:
```suggestion
        # rx.adj(angle) = u3.adj(angle, -pi/2, pi/2)
```

**Review by boschmitt — APPROVED** [review]
Thanks for the work Eric. Couple of suggestions to fix the comments too.

**Review by khalatepradnya — APPROVED** [review]
LGTM! Thanks, Eric.
