### PR TITLE
Fix #251: Base profile should handle single qubit allocations.

### LINKED ISSUE #251: Lowering single qubit allocations to base profile
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

There seems to be a bug when using single qubit allocations and lowering to the base profile.

### Steps to reproduce the bug

Given the following kernel:

```cpp
#include <cudaq.h>
#include <iostream>

struct ak2 {
  void operator()() __qpu__ {
    cudaq::qubit q;
    h(q);
    mz(q);
  }
};

int main() {
  auto counts = cudaq::sample(ak2{});
  std::cout << "Test: ";
  counts.dump();
  return 0;
}
```

After compiling targeting Quantinuum backend (which will run using the mock server):
```bash
nvq++ --enable-mlir -v /test_kernel.cpp -o test_kernel.x --target quantinuum --quantinuum-url http://localhost:6245
```

We get an error when trying to run the executable:
```
# ./test_kernel.x
loc("-":4:8): error: could not trace offset value
```

### Expected behavior

Lowering to base profile should be able to handle single qubit allocations.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **C++ compiler**: gcc-12
- **Operating system**: Ubuntu (AArch64)

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by schweitzpgi**
This is a direct fix to handle both array and single qubit allocations in the base profile pass.

Add a pass to combine quantum allocations.

### CODE REVIEW

File: test/NVQPP/bug_qubit.cpp [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+ * Copyright (c) 2022 - 2023 NVIDIA Corporation & Affiliates.                  *
+ * All rights reserved.                                                        *
+ *                                                                             *
+ * This source code and the accompanying materials are made available under    *
+ * the terms of the Apache License 2.0 which accompanies this distribution.    *
+ ******************************************************************************/
+
+// This code is from Issue 251.
+
+// RUN: nvq++ --enable-mlir -v %s --target quantinuum --quantinuum-url http://localhost:6245 && ( ./a.out > %t 2>&1 || ( cat %t | FileCheck %s ) )
```
Comment (amccaskey) [inline test/NVQPP/bug_qubit.cpp:11]: I think you can reproduce this without relying on the failure caused by no quantinuum mock server - just use `--target quantinuum --emulate`

Comment (schweitzpgi) [reply test/NVQPP/bug_qubit.cpp:11]: OK. I xeroxed the test case from #251 here and wasn't sure what, if anything, I should change.
