### PR TITLE
Fix #296: if issue in JIT compile.

### LINKED ISSUE #296: Failing to compile `if` statements to quantinuum target
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When targeting quantinuum, the compiler seems to fail lowering `if` statements. 

### Steps to reproduce the bug

Let `foo.cpp` be:
```cpp
#include <cudaq.h>

__qpu__ void foo(bool value) {
  cudaq::qubit q;
  if (value)
    x(q);
  mz(q);
}

int main() {
  auto result = cudaq::sample(100, foo, true);
  result.dump();
  return 0;
}
```

Compiling with: `nvq++ -v foo.cpp -o foo --target quantinuum --emulate` and then executing it, `./foo`, we get:
```console
llvm/ADT/ilist_iterator.h:138: llvm::ilist_iterator<OptionsT, IsReverse, IsConst>::reference llvm::ilist_iterator<OptionsT, IsReverse, IsConst>::operator*() const [with OptionsT = llvm::ilist_detail::node_options<mlir::Block, true, false, void>; bool IsReverse = true; bool IsConst = false; reference = mlir::Block&]: Assertion `!NodePtr->isKnownSentinel()' failed.
Aborted (core dumped)
```

I also tried `if (true)`. I get the same error.

### Expected behavior

Get the correct result: `{ 1:100 }` (when value is `true`), `{ 0:100 }` otherwise.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: main
- **C++ compiler**: gcc 12
- **Operating system**: Ubuntu 22.04 (docker)

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by schweitzpgi**

### CODE REVIEW

File: test/NVQPP/if_jit.cpp [hunk 1]
```diff
@@ -0,0 +1,26 @@
+/*******************************************************************************
+ * Copyright (c) 2022 - 2023 NVIDIA Corporation & Affiliates.                  *
+ * All rights reserved.                                                        *
+ *                                                                             *
+ * This source code and the accompanying materials are made available under    *
+ * the terms of the Apache License 2.0 which accompanies this distribution.    *
+ ******************************************************************************/
+
+// RUN: nvq++ %s --target quantinuum --emulate && ./a.out | FileCheck %s
```
Comment (boschmitt) [inline test/NVQPP/if_jit.cpp:9]: If we have multiple tests that compile without setting `-o <something>`, couldn't we have conflicts with the `a.out` name ?

```suggestion
// RUN: nvq++ %s -o %basename_t.x --target quantinuum --emulate && ./%basename_t.x | FileCheck %s
```

Comment (boschmitt) [reply test/NVQPP/if_jit.cpp:9]: In my build I got all in the same directory:
```
build/test/NVQPP/a.out
build/test/NVQPP/include.x
build/test/NVQPP/introspection.x
build/test/NVQPP/out_auto_kernel.x
build/test/NVQPP/out_testdcl.x
build/test/NVQPP/out_testifstmts.x
build/test/NVQPP/out_testlambdaI.x
build/test/NVQPP/out_testTemplateI.x
```
There is already a `a.out` from `test/NVQPP/bug_qubit.cpp`

Comment (schweitzpgi) [reply test/NVQPP/if_jit.cpp:9]: Ok. Thanks.

**Review by boschmitt — APPROVED** [review]
