### PR TITLE
Fix #379, cu1 -> u1 (bad copy-paste)

### LINKED ISSUE #379: `r1` gate isn't correctly translated to OpenQASM
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

When translating Quake to OpenQASM, `r1` gates are translated to `cu1` gates instead of `u1` gates.

### Steps to reproduce the bug

Compile the following code with `nvq++ kernel.cpp`:
```c++
#include <cudaq.h>

#include <numbers>
#include <iostream>

int main() {
        auto kernel = cudaq::make_kernel();
        auto qubit = kernel.qalloc(1);
        kernel.r1(std::numbers::pi_v<double>, qubit[0]);
        kernel.mz(qubit[0]);
        std::string to_replace = "367535629127()";
        std::string replacement = "367535629127() attributes {\"cudaq-entrypoint\"}";
        std::string quake = kernel.to_quake();
        std::cout << quake.replace(quake.find(to_replace), to_replace.size(), replacement) << std::endl;
        return 0;
}
```

The result is the following MLIR code:
```
module {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_367535629127() attributes {"cudaq-entrypoint"} {
    %cst = arith.constant 3.1415926535897931 : f64
    %0 = quake.alloca !quake.veq<1>
    %1 = quake.extract_ref %0[0] : (!quake.veq<1>) -> !quake.ref
    quake.r1 (%cst) %1 : (f64, !quake.ref) -> ()
    %2 = quake.mz %1 : (!quake.ref) -> i1 {registerName = ""}
    return
  }
}
```

Translate the MLIR code to OpenQASM with `cudaq-translate --convert-to=openqasm kernel.qke`. The output is:
```
// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

qreg var0[1];
cu1(3.141593e+00) var0[0];
creg var2[1];
measure var0[0] -> var2[0];
```

### Expected behavior

The resulting OpenQASM code should be:
```
// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

qreg var0[1];
u1(3.141593e+00) var0[0];
creg var2[1];
measure var0[0] -> var2[0];
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **`cuda-quantum` docker image version**: sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d. Download using docker pull ghcr.io/nvidia/cuda-quantum@sha256:337d6e846edfd6c41cde2e89d60ea223aaf2ecdc7d6d2f86797ecfa04497483d

### Suggestions

This can p robably be solved by applying the following change to the translation code:
```diff
-    name = StringSwitch<StringRef>(qkeName).Case("r1", "cu1").Default(qkeName);
+    name = StringSwitch<StringRef>(qkeName).Case("r1", "u1").Default(qkeName);
```

https://github.com/NVIDIA/cuda-quantum/blob/571bbe9f78d084044d7d54f69bc7f619dafdff0e/lib/Target/OpenQASM/TranslateToOpenQASM.cpp#L29

### PR DESCRIPTION
**Pull request by amccaskey**
Also implement 
```cpp
std::ostream &operator<<(std::ostream &stream,
                                  const kernel_builder_base &builder);
```
so users can write kernel_builders to ostream 
```cpp
std::cout << kernel << "\n";
```

### CODE REVIEW

File: runtime/cudaq/builder/kernel_builder.h [hunk 1]
```diff
@@ -310,6 +310,14 @@ class kernel_builder_base {
   virtual std::string to_quake() const = 0;
   virtual void jitCode(std::vector<std::string> extraLibPaths = {}) = 0;
   virtual ~kernel_builder_base() = default;
+
+  /// @brief Write the kernel_builder to the given output stream.
+  /// This outputs the Quake representation.
+  friend std::ostream &operator<<(std::ostream &stream,
```
Comment (schweitzpgi) [inline runtime/cudaq/builder/kernel_builder.h:316]: This may need an attribute to make sure the linker doesn't throw it away. Not sure.

**Review by schweitzpgi — APPROVED** [review]
