### PR TITLE
Fix WireType compliance issues with qubit-mapping pass

### LINKED ISSUE #928: qubit-mapping has bug threading wire values
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [x] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

With pedantic checking enabled:
```console
% nvq++ -v --target iqm --iqm-machine Adonis --emulate $SRC/test/NVQPP/cudaq_observe.cpp
% ./a.out
error: 'quake.swap' op wires are a linear type and must have exactly one use
```
This error occurs after the `qubit-mapping` pass is run.

The MLIR is
```c++
"builtin.module"() ({
  "func.func"() ({
    %0 = "arith.constant"() {value = 1.5707963267948966 : f64} : () -> f64
    %1 = "arith.constant"() {value = 3.1415926535897931 : f64} : () -> f64
    %2 = "arith.constant"() {value = 0.000000e+00 : f64} : () -> f64
    %3 = "arith.constant"() {value = 5.900000e-01 : f64} : () -> f64
    %4 = "quake.null_wire"() : () -> !quake.wire
    %5 = "quake.null_wire"() : () -> !quake.wire
    %6 = "quake.null_wire"() : () -> !quake.wire
    %7 = "quake.phased_rx"(%1, %2, %4) {operand_segment_sizes = array<i32: 2, 0, 1>} : (f64, f64, !quake.wire) -> !quake.wire
    %8 = "quake.phased_rx"(%3, %0, %5) {operand_segment_sizes = array<i32: 2, 0, 1>} : (f64, f64, !quake.wire) -> !quake.wire
    %9 = "quake.phased_rx"(%0, %0, %7) {operand_segment_sizes = array<i32: 2, 0, 1>} : (f64, f64, !quake.wire) -> !quake.wire
    %10 = "quake.phased_rx"(%1, %2, %9) {operand_segment_sizes = array<i32: 2, 0, 1>} : (f64, f64, !quake.wire) -> !quake.wire
    %11:2 = "quake.swap"(%8, %6) {operand_segment_sizes = array<i32: 0, 0, 2>} : (!quake.wire, !quake.wire) -> (!quake.wire, !quake.wire)
    %12:2 = "quake.z"(%11#1, %10) {operand_segment_sizes = array<i32: 0, 1, 1>} : (!quake.wire, !quake.wire) -> (!quake.wire, !quake.wire)
    %13 = "quake.phased_rx"(%0, %0, %12#1) {operand_segment_sizes = array<i32: 2, 0, 1>} : (f64, f64, !quake.wire) -> !quake.wire
    %14 = "quake.phased_rx"(%1, %2, %13) {operand_segment_sizes = array<i32: 2, 0, 1>} : (f64, f64, !quake.wire) -> !quake.wire
    "quake.sink"(%14) : (!quake.wire) -> ()
    "quake.sink"(%12#0) : (!quake.wire) -> ()
    "func.return"() : () -> ()
  }) {"cudaq-entrypoint", "cudaq-kernel", function_type = () -> (), mapping_v2p = [0, 2], sym_name = "__nvqpp__mlirgen__ansatz"} : () -> ()
}) : () -> ()
```
We can see that there is no use of the wire `%11#0`, which is a violation of wire values being used exactly once.

### Steps to reproduce the bug

See code in test cudaq_observe.cpp

### Expected behavior

All values of type `!quake.wire` type are expected to be used exactly once.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: proto-0.6.0-developer
- **Python version**: 
- **C++ compiler**: 
- **Operating system**: 

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by bmhowe23**
* qubit-mapping pass updated to remove sinks prior to processing and add them back in at the end of the pass
* Update tests
* Update CircuitCheck to fix a memory corruption issue due to invalid DenseMap usage

Resolves #928

### CODE REVIEW

File: lib/Optimizer/Transforms/Mapping.cpp [hunk 1]
```diff
@@ -671,11 +680,19 @@ struct Mapper : public cudaq::opt::impl::MappingPassBase<Mapper> {
...
       else
         break;
     }
+    // Add sinks where needed
+    auto wireType = builder.getType<quake::WireType>();
+    builder.setInsertionPoint(block.getTerminator());
+    block.walk([&](Operation *op) {
+      for (auto r : op->getResults())
+        if (r.use_empty() && r.getType() == wireType)
+          builder.create<quake::SinkOp>(builder.getUnknownLoc(), r);
```
Comment (schweitzpgi) [inline lib/Optimizer/Transforms/Mapping.cpp:694]:
```suggestion
          builder.create<quake::SinkOp>(op->getLoc(), r);
```
might be better than using nothing?

File: utils/CircuitCheck/UnitaryBuilder.cpp [hunk 2]
```diff
@@ -53,7 +53,7 @@ LogicalResult UnitaryBuilder::build(func::FuncOp func) {
 
       for (auto &&[newQuantumOp, quantumOp] : llvm::zip(
                quake::getQuantumResults(op), quake::getQuantumOperands(op)))
-        qubitMap[newQuantumOp] = qubitMap[quantumOp];
+        qubitMap.insert({newQuantumOp, qubitMap[quantumOp]});
```
Comment (schweitzpgi) [inline utils/CircuitCheck/UnitaryBuilder.cpp:56]: Is the intention here to overwrite the lhs if it is already in the map? If so, then `insert` is going to be frustrating since it only does the insertion if the key is NOT in the map already.

**Review by schweitzpgi — COMMENTED** [review]
Cool! Thanks, Ben.

This fixes some of the same tests, I touched in my working branch.

Let me try your changes with my stricter type checking on my end.

File: lib/Optimizer/Transforms/Mapping.cpp (hunk 1 above)
Comment (bmhowe23) [reply lib/Optimizer/Transforms/Mapping.cpp:694]: Good point. I suspect some of them will still end up with unknown locations because the injected swaps have unknown locations, but this will indeed provide valid locations for some of them.

File: utils/CircuitCheck/UnitaryBuilder.cpp (hunk 2 above)
Comment (bmhowe23) [reply utils/CircuitCheck/UnitaryBuilder.cpp:56]: > Is the intention here to overwrite the lhs if it is already in the map? If so, then `insert` is going to be frustrating since it only does the insertion if the key is NOT in the map already.

No, `newQuantumOp` won't exist in `qubitMap[]` yet because we're `func.walk`-ing the block, and this is a new result coming from the operation being walked, so it should always indeed be inserting here, so I think we should be safe here.

**Review by schweitzpgi — APPROVED** [review]
+1

File: utils/CircuitCheck/UnitaryBuilder.cpp [hunk 3]
```diff
@@ -234,7 +234,7 @@ void UnitaryBuilder::growMatrix(unsigned numQubits) {
 //     q : ─┤    ├┤ U ├─   ─┤    ├┤ U ├─   ─┤    ├┤     ├─   ─┤    ├─
 //      0   │    │└───┘     │    │└───┘     │    ││     │     │    │
 //          │    │          │    │┌───┐     │    ││     │     │    │
-//     q : ─┤ C  ├────── = ─┤ C  ├┤   ├─ = ─┤ C  ├┤ I⊗U ├─ = ─┤ C  ├─
+//     q : ─┤ C  ├────── = ─┤ C  ├┤   ├─ = ─┤ C  ├┤ I⊗U├─ = ─┤ C  ├─
```
Comment (boschmitt) [inline utils/CircuitCheck/UnitaryBuilder.cpp:237]: I don't think we wan to delete this space.

File: lib/Optimizer/Transforms/Mapping.cpp [hunk 4]
```diff
@@ -671,11 +680,19 @@ struct Mapper : public cudaq::opt::impl::MappingPassBase<Mapper> {
...
         break;
     }
+    // Add sinks where needed
+    auto wireType = builder.getType<quake::WireType>();
+    builder.setInsertionPoint(block.getTerminator());
+    block.walk([&](Operation *op) {
+      for (auto r : op->getResults())
+        if (r.use_empty() && r.getType() == wireType)
+          builder.create<quake::SinkOp>(op->getLoc(), r);
+    });
```
Comment (boschmitt) [inline lib/Optimizer/Transforms/Mapping.cpp:695]: Another possibility would be to use the `phyToWire` vector in the router to place the sinks. This structure should hold the last wire corresponding to each qubit. This way, we wouldn't need to revisit the operation in the block. (I'm not sure if the performance gain would be substantial given the size of the circuits we currently deal with.)

**Review by boschmitt — COMMENTED** [review]
LGTM. Thanks Ben!

File: utils/CircuitCheck/UnitaryBuilder.cpp (hunk 3 above)
Comment (bmhowe23) [reply utils/CircuitCheck/UnitaryBuilder.cpp]: Updated in c844c7fd

File: lib/Optimizer/Transforms/Mapping.cpp (hunk 4 above)
Comment (bmhowe23) [reply lib/Optimizer/Transforms/Mapping.cpp]: Good idea. Updated in c844c7fd.
