### PR TITLE
Fix #627: Code gen for IQM Json failure.

### LINKED ISSUE #627: Runtime error during lowering for IQM test
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

The `test/NVQPP/integration/qspan_slices.cpp` test fails when targeting IQM. It returns this error:
```
loc(callsite("qspan_slices.cpp":15:19 at "qspan_slices.cpp":23:3)): error: 'quake.subveq' op unable to translate op to IQM Json quake.subveq
```
This test is currently disabled in our Nightly Integration tests because of this error.

### Steps to reproduce the bug

```bash
root@docker-desktop:/workspaces/cuda-quantum/build# nvq++ ../test/NVQPP/integration/qspan_slices.cpp --target iqm --iqm-machine Adonis --emulate
root@docker-desktop:/workspaces/cuda-quantum/build# ./a.out 
loc(callsite("qspan_slices.cpp":15:19 at "qspan_slices.cpp":23:3)): error: 'quake.subveq' op unable to translate op to IQM Json quake.subveq
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not successfully translate to iqm.
Aborted
```

### Expected behavior

It should run without errors like the other platforms. For example:
```
root@docker-desktop:/workspaces/cuda-quantum/build# nvq++ ../test/NVQPP/integration/qspan_slices.cpp --target quantinuum --emulate
root@docker-desktop:/workspaces/cuda-quantum/build# ./a.out 
1110
```

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: 26699751
- **Python version**: N/A
- **C++ compiler**: 16.0.0
- **Operating system**: Ubuntu 22.04

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by schweitzpgi**
These changes allow all the code gen backends to use a pass pipeline to fix up the code before the actual file is written. In the case of the bug, there was still Quake IR sitting in the Module that needed to be transformed before it could be emitted correctly.

### CODE REVIEW

File: runtime/common/RuntimeMLIR.cpp [hunk 1]
```diff
@@ -391,12 +379,19 @@ void registerToIQMJsonTranslation() {
...
       [](Operation *op, llvm::raw_string_ostream &output, bool printIR,
          bool printIntermediateMLIR) {
-        auto passed = cudaq::translateToIQMJson(op, output);
+        PassManager pm(op->getContext());
         if (printIntermediateMLIR)
-          llvm::errs() << "WARNING: printIntermediateMLIR not supported for "
-                          "IQM's json format\n";
-        if (printIR)
-          llvm::errs() << output.str();
+          pm.enableIRPrinting();
```
Comment (bmhowe23) [inline runtime/common/RuntimeMLIR.cpp:384]: Thanks for updating this path to support the new `printIntermediateMLIR`.

**Review by bmhowe23 — APPROVED** [review]
LGTM. Thanks, Eric!
